"""
Plugin template generator for First Contact.

Scaffolds a new plugin with correct directory structure, metadata, and
stub code that's immediately loadable by the plugin system.

Usage:
    python plugin_generator.py my_cool_plugin
    python plugin_generator.py my_cool_plugin --description "Fetches weather data"
    python plugin_generator.py my_cool_plugin --tools 3

Can also be imported and called programmatically:
    from plugin_generator import generate_plugin
    generate_plugin("my_plugin", description="...", tools_count=2)
"""

import argparse
import json
import keyword
import os
import sys


PLUGINS_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "plugins")

RESERVED_NAMES = {"example_plugin", "__pycache__"}


def validate_name(name):
    """Validate a plugin name. Returns error message or None if valid."""
    if not name.isidentifier():
        return (
            f"'{name}' is not a valid plugin name. "
            "Use only letters, numbers, and underscores (can't start with a number)."
        )
    if keyword.iskeyword(name):
        return f"'{name}' is a Python keyword and can't be used as a plugin name."
    if name in RESERVED_NAMES:
        return f"'{name}' is a reserved name."
    return None


def _render_init_py(name, description, tools_count):
    """Generate the __init__.py content for a plugin."""
    display_name = name.replace("_", " ").title()

    # Build tool definitions
    tool_names = []
    tool_lines = []
    for i in range(1, tools_count + 1):
        suffix = f"_{i}" if tools_count > 1 else ""
        tool_name = f"{name}{suffix}"
        tool_names.append(tool_name)
        tool_lines.extend([
            '        {',
            f'            "name": "{tool_name}",',
            '            "description": "Tool description — replace with actual description.",',
            '            "input_schema": {',
            '                "type": "object",',
            '                "properties": {',
            '                    "input": {',
            '                        "type": "string",',
            '                        "description": "Input parameter — replace with actual parameters.",',
            '                    },',
            '                },',
            '                "required": ["input"],',
            '            },',
            '        },',
        ])
    tools_block = "\n".join(tool_lines)

    # Build execute routing
    routing_lines = []
    for idx, tn in enumerate(tool_names):
        kw = "if" if idx == 0 else "elif"
        routing_lines.extend([
            f'    {kw} tool_name == "{tn}":',
            f'        # TODO: implement {tn}',
            f'        return f"Result: {{tool_input.get(\'input\', \'\')}}", False',
        ])
    routing_block = "\n".join(routing_lines)

    lines = [
        '"""',
        f'Plugin: {display_name}',
        'Generated by First Contact plugin generator',
        '',
        'Plugin API:',
        '- PLUGIN_NAME: str — display name',
        '- PLUGIN_DESCRIPTION: str — short description',
        '- PLUGIN_VERSION: str — semver version',
        '- get_tools() -> list[dict] — return tool definitions',
        '- execute(tool_name, tool_input, config, history) -> tuple[str, bool] — execute a tool call',
        '  Returns (result_text, is_error)',
        '"""',
        '',
        '# --- Plugin metadata ---',
        '',
        f'PLUGIN_NAME = "{display_name}"',
        f'PLUGIN_DESCRIPTION = "{description}"',
        'PLUGIN_VERSION = "0.1.0"',
        '',
        '',
        '# --- Tool definitions ---',
        '',
        'def get_tools():',
        '    """Return tool definitions for this plugin."""',
        '    return [',
        tools_block,
        '    ]',
        '',
        '',
        'TOOLS = get_tools()',
        '',
        '',
        '# --- Tool execution ---',
        '',
        'def execute(tool_name, tool_input, config, conversation_history):',
        '    """Execute a tool call. Returns (result_text, is_error)."""',
        routing_block,
        '    return f"Unknown tool: {tool_name}", True',
        '',
    ]
    return "\n".join(lines) + "\n"


def _render_readme(name, description, tools_count):
    """Generate the README.md content for a plugin."""
    display_name = name.replace("_", " ").title()

    tool_rows = []
    for i in range(1, tools_count + 1):
        suffix = f"_{i}" if tools_count > 1 else ""
        tool_name = f"{name}{suffix}"
        tool_rows.append(f"| `{tool_name}` | Tool description |")
    tool_table = "\n".join(tool_rows)

    return (
        f"# {display_name}\n"
        f"\n"
        f"{description}\n"
        f"\n"
        f"## Installation\n"
        f"\n"
        f"Copy this directory into the `plugins/` folder of your First Contact installation:\n"
        f"\n"
        f"```bash\n"
        f"cp -r {name}/ /path/to/first-contact/plugins/\n"
        f"```\n"
        f"\n"
        f"Restart First Contact or run `/plugins reload` to load the plugin.\n"
        f"\n"
        f"## Tools\n"
        f"\n"
        f"| Tool | Description |\n"
        f"|------|-------------|\n"
        f"{tool_table}\n"
        f"\n"
        f"## Configuration\n"
        f"\n"
        f"This plugin does not require any configuration. If you add config keys,\n"
        f"they will be accessible via the `config` parameter in `execute()`.\n"
    )


def _render_plugin_json(name, description):
    """Generate the plugin.json metadata."""
    return {
        "name": name,
        "version": "0.1.0",
        "description": description,
        "author": "",
        "license": "MIT",
        "homepage": "",
        "min_version": "1.0.0",
        "dependencies": [],
    }


def generate_plugin(name, description=None, tools_count=1, output_dir=None):
    """Generate a plugin directory with all scaffolding files.

    Args:
        name: Plugin name (valid Python identifier)
        description: Short description (default: generated from name)
        tools_count: Number of stub tools to generate (default: 1)
        output_dir: Base directory for plugins (default: plugins/)

    Returns:
        Path to the created plugin directory.

    Raises:
        ValueError: If the name is invalid or directory already exists.
    """
    error = validate_name(name)
    if error:
        raise ValueError(error)

    if tools_count < 1:
        tools_count = 1

    if description is None:
        display = name.replace("_", " ").title()
        description = f"A First Contact plugin — {display}"

    if output_dir is None:
        output_dir = PLUGINS_DIR

    plugin_dir = os.path.join(output_dir, name)
    if os.path.exists(plugin_dir):
        raise ValueError(
            f"Plugin directory already exists: {plugin_dir}\n"
            "Remove it first or choose a different name."
        )

    os.makedirs(plugin_dir, exist_ok=True)

    # __init__.py
    init_content = _render_init_py(name, description, tools_count)
    with open(os.path.join(plugin_dir, "__init__.py"), "w") as f:
        f.write(init_content)

    # README.md
    readme_content = _render_readme(name, description, tools_count)
    with open(os.path.join(plugin_dir, "README.md"), "w") as f:
        f.write(readme_content)

    # plugin.json
    meta = _render_plugin_json(name, description)
    with open(os.path.join(plugin_dir, "plugin.json"), "w") as f:
        json.dump(meta, f, indent=2)
        f.write("\n")

    return plugin_dir


def main():
    parser = argparse.ArgumentParser(
        description="Generate a new First Contact plugin from template.",
    )
    parser.add_argument(
        "name",
        help="Plugin name (valid Python identifier, e.g. my_cool_plugin)",
    )
    parser.add_argument(
        "--description", "-d",
        default=None,
        help="Short description of the plugin",
    )
    parser.add_argument(
        "--tools", "-t",
        type=int,
        default=1,
        help="Number of stub tools to generate (default: 1)",
    )

    args = parser.parse_args()

    try:
        plugin_dir = generate_plugin(
            args.name,
            description=args.description,
            tools_count=args.tools,
        )
    except ValueError as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)

    print(f"Created plugin '{args.name}' at {plugin_dir}/")
    print(f"  Edit {plugin_dir}/__init__.py to add your tool logic.")
    print("  Restart First Contact to load the plugin.")


if __name__ == "__main__":
    main()
